### ISSUE TITLE
bigrams() does not work correctly with text that includes only one word

### ISSUE THREAD

**Issue by andreskull** [kbenoit/quanteda#33]
> bigrams("banking", include.unigrams = FALSE)
[[1]]
[1] "banking_" "_banking"

**Comment by kbenoit** [comment]
I think it's fixed now, in the dev branch, see ?corpus.
``` s
tmCorp <- VCorpus(VectorSource(inaugTexts[49:57]))
quantCorp <- corpus(tmCorp)
summary(quantCorp)
#> Corpus consisting of 9 documents.
#> 
#>          Text Types Tokens Sentences
#>   1981-Reagan   842   2431       135
#>   1985-Reagan   854   2551       127
#>     1989-Bush   747   2315       147
#>  1993-Clinton   598   1597        81
#>  1997-Clinton   714   2148       111
#>     2001-Bush   584   1581        97
#>     2005-Bush   724   2070       100
#>    2009-Obama   893   2390       119
#>    2013-Obama   773   2092        89
```

**Comment by andreskull** [comment]
the reported bigrams issue is not fixed. 
you mention here the fixing of corpus(VCorpus) issue that was issued here https://github.com/kbenoit/quanteda/issues/34.

**Comment by kbenoit** [comment]
This is fixed now through the completely overhauled `ngrams()` function. e.g.

    > ngrams(tokenize("banking", simplify = TRUE), n = 1:2)
    [1] "banking"
    > ngrams(tokenize("banking", simplify = TRUE), n = 2) 
    NULL
