### ISSUE TITLE
creating corpus from tm VCorpus fails

### ISSUE THREAD

**Issue by andreskull** [kbenoit/quanteda#34]
> class(corp)
[1] "VCorpus" "Corpus" 
> corp2 <- corpus(corp)
Error in `[.data.frame`(metad, , c(1, 3:15)) : undefined columns selected

**Comment by andreskull** [comment]
This is fixed now.

**Comment by toddntucker** [comment]
I am still getting this error message. How did you resolve this?

**Comment by andreskull** [comment]
It might be that the fix is still in the development branch.

**Comment by kbenoit** [comment]
Yes, we fixed this issue in the dev branch (hence this issue is closed). Not fixed in the CRAN version yet though - we are readying more changes before submitting an update to CRAN. If you still encounter the problem, please send me the VCorpus object and I will fix the code.
